name = "LagrangianDescriptors"
uuid = "a4733523-375c-482b-97f9-45e4d053eacd"
authors = ["Ricardo Rosa <rmsrosa@gmail.com>"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
examples = ["Test", "OrdinaryDiffEq", "LinearAlgebra", "QuadGK", "BenchmarkTools"]
test = ["Test", "OrdinaryDiffEq", "LinearAlgebra", "QuadGK", "BenchmarkTools"]
